services:
  lb:
    image: haproxy:3.0-alpine
    cpus: "0.20"
    mem_limit: "24MB"
    ports:
      - "9999:9999"
    volumes:
      - ./deploy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "24MB"

  api1:
    image: ghcr.io/leofmarciano/rinha-de-backend-2026:6e6f6b7ad5f94d9cbe1c29fb92a4a7b7c7cbaf1b
    platform: linux/amd64
    cpus: "0.40"
    mem_limit: "163MB"
    environment: &api-env
      PORT: "8080"
      SOCKET_PATH: "/sockets/api1.sock"
      INDEX_PATH: "/app/build/index_k8192.ivfi16"
      BASE_NPROBE: "20"
      AMBIG_NPROBE: "40"
      BBOX_MODE: "ambiguous-only"
      USE_EXACT_FALLBACK: "0"
      USE_FAST_PATH: "0"
      HEURISTIC_ONLY: "0"
      WARMUP: "full"
      WORKERS: "1"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "163MB"

  api2:
    image: ghcr.io/leofmarciano/rinha-de-backend-2026:6e6f6b7ad5f94d9cbe1c29fb92a4a7b7c7cbaf1b
    platform: linux/amd64
    cpus: "0.40"
    mem_limit: "163MB"
    environment:
      <<: *api-env
      SOCKET_PATH: "/sockets/api2.sock"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "163MB"

volumes:
  sockets:
